# apiVersion: v1
# kind: Service
# metadata:
#   name: ecommerce-service
#   namespace: "2401080"
# spec:
#   type: NodePort
#   selector:
#     app: ecommerce
#   ports:
#     - port: 5000
#       targetPort: 5000
#       nodePort: 30077



# FRONTEND SERVICE
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-service
  namespace: "2401080"
spec:
  type: NodePort
  selector:
    app: ecommerce-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000

---
# BACKEND SERVICE
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend-service
  namespace: "2401080"
spec:
  type: NodePort
  selector:
    app: ecommerce-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32001
