# apiVersion: v1
# kind: Service
# metadata:
#   name: ecommerce-service
#   namespace: "2401080"
# spec:
#   type: NodePort
#   selector:
#     app: ecommerce
#   ports:
#     - port: 5000
#       targetPort: 5000
#       nodePort: 30077



# FRONTEND SERVICE
# apiVersion: v1
# kind: Service
# metadata:
#   name: ecommerce-frontend-service
#   namespace: "2401080"
# spec:
#   type: NodePort
#   selector:
#     app: ecommerce-frontend
#   ports:
#     - port: 3000
#       targetPort: 3000
#       nodePort: 32000

# ---
# # BACKEND SERVICE
# apiVersion: v1
# kind: Service
# metadata:
#   name: ecommerce-backend-service
#   namespace: "2401080"
# spec:
#   type: NodePort
#   selector:
#     app: ecommerce-backend
#   ports:
#     - port: 5000
#       targetPort: 5000
#       nodePort: 32001


# apiVersion: v1
# kind: Service
# metadata:
#   name: ecommerce-frontend-service
#   namespace: "2401080"
# spec:
#   type: NodePort
#   selector:
#     app: ecommerce-frontend
#   ports:
#     - port: 3000
#       targetPort: 3000
#       nodePort: 32000

# apiVersion: v1
# kind: Service
# metadata:
#   name: ecommerce-backend-service
#   namespace: "2401080"
# spec:
#   type: NodePort
#   selector:
#     app: ecommerce-backend
#   ports:
#     - port: 5000
#       targetPort: 5000
#       nodePort: 32001





# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ecommerce-ingress
#   namespace: "2401080"
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: suvarnarup-ecommerce.imcc.com

#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: ecommerce-frontend-service
#                 port:
#                   number: 3000

#           - path: /api
#             pathType: Prefix
#             backend:
#               service:
#                 name: ecommerce-backend-service
#                 port:
#                   number: 5000



#test

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ecommerce-ingress
#   namespace: "2401080"
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: suvarnarup-ecommerce.imcc.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: ecommerce-frontend-service
#                 port:
#                   number: 3000

#           - path: /api
#             pathType: Prefix
#             backend:
#               service:
#                 name: ecommerce-backend-service
#                 port:
#                   number: 5000


#28/11

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: "2401080"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: suvarnarup-ecommerce.imcc.com
      http:
        paths:
          # FRONTEND (React)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-frontend-service
                port:
                  number: 3000

          # BACKEND (Node.js API)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ecommerce-backend-service
                port:
                  number: 5000


